local M = {}

-- Other editors. The role map is the one the Neovim groups use, so a keyword is
-- cinder here for the same reason it is cinder there.

local palette = require("cendre.palette")

--- @param bg string
--- @return string
function M.vim(bg)
  local c = palette.get(bg)

  --- @param group string
  --- @param fg string|nil
  --- @param bgc string|nil
  --- @param gui string|nil
  --- @return string
  local function hi(group, fg, bgc, gui)
    local parts = { ("hi %-16s"):format(group) }
    if fg then table.insert(parts, "guifg=" .. fg) end
    if bgc then table.insert(parts, "guibg=" .. bgc) end
    if gui then table.insert(parts, "gui=" .. gui) end
    return table.concat(parts, " ")
  end

  local lines = {
    '" cendre · ' .. bg .. " · https://github.com/Aejkatappaja/cendre",
    '" generated by scripts/extras.lua, do not edit',
    "",
    "set background=dark",
    "hi clear",
    'if exists("syntax_on")',
    "  syntax reset",
    "endif",
    ('let g:colors_name = "%s"'):format(palette.name(bg)),
    "",
    "if !has('gui_running') && &t_Co < 256",
    "  finish",
    "endif",
    "",
    '" editor',
    hi("Normal", c.fg, c.bg0),
    hi("NormalFloat", c.fg, c.bg_deep),
    hi("Cursor", c.bg0, c.ember),
    hi("CursorLine", nil, c.bg1, "NONE"),
    hi("CursorLineNr", c.ember, nil, "bold"),
    hi("LineNr", c.gutter),
    hi("SignColumn", c.gutter, "NONE"),
    hi("VertSplit", c.bg3, "NONE"),
    hi("StatusLine", c.fg_dim, c.bg2),
    hi("StatusLineNC", c.gutter, c.bg1),
    hi("TabLine", c.comment, c.bg1),
    hi("TabLineFill", nil, c.bg1),
    hi("TabLineSel", c.fg, c.bg0, "bold"),
    hi("Pmenu", c.fg, c.bg1),
    hi("PmenuSel", c.bg0, c.ember, "bold"),
    hi("PmenuSbar", nil, c.bg2),
    hi("PmenuThumb", nil, c.bg4),
    hi("Visual", nil, c.vis),
    hi("Search", c.bg0, c.brass),
    hi("IncSearch", c.bg0, c.ember),
    hi("MatchParen", c.ember, nil, "bold"),
    hi("Folded", c.comment, c.bg1),
    hi("NonText", c.bg4),
    hi("SpecialKey", c.bg4),
    hi("Directory", c.frost),
    hi("Title", c.ember, nil, "bold"),
    hi("Conceal", c.comment),
    hi("QuickFixLine", nil, c.bg2, "bold"),
    hi("WildMenu", c.bg0, c.ember),
    hi("ColorColumn", nil, c.bg1),
    "",
    '" messages',
    hi("ModeMsg", c.ember, nil, "bold"),
    hi("MoreMsg", c.info),
    hi("Question", c.info),
    hi("ErrorMsg", c.error, nil, "bold"),
    hi("WarningMsg", c.warn),
    "",
    '" syntax. one role, one pigment',
    hi("Comment", c.comment, nil, "italic"),
    hi("Constant", c.sap),
    hi("String", c.sap),
    hi("Character", c.sap),
    hi("Number", c.sap),
    hi("Float", c.sap),
    hi("Boolean", c.sap),
    hi("Identifier", c.fg, nil, "NONE"),
    hi("Function", c.brass),
    hi("Statement", c.cinder, nil, "NONE"),
    hi("Conditional", c.cinder),
    hi("Repeat", c.cinder),
    hi("Label", c.cinder),
    hi("Keyword", c.cinder),
    hi("Exception", c.cinder),
    hi("Operator", c.fg_dim),
    hi("PreProc", c.cinder),
    hi("Include", c.cinder),
    hi("Define", c.cinder),
    hi("Macro", c.ember),
    hi("PreCondit", c.cinder),
    hi("Type", c.frost, nil, "NONE"),
    hi("StorageClass", c.cinder),
    hi("Structure", c.frost),
    hi("Typedef", c.frost),
    hi("Special", c.ember),
    hi("SpecialChar", c.ember),
    hi("Tag", c.cinder),
    hi("Delimiter", c.fg_dim),
    hi("SpecialComment", c.comment, nil, "italic"),
    hi("Debug", c.error),
    hi("Underlined", nil, nil, "underline"),
    hi("Ignore", c.gutter),
    hi("Error", c.error),
    hi("Todo", c.bg0, c.warn, "bold"),
    "",
    '" diff',
    hi("DiffAdd", nil, c.add),
    hi("DiffDelete", nil, c.del),
    hi("DiffChange", nil, c.mod),
    hi("DiffText", nil, c.bg3, "bold"),
    "",
    '" spell',
    "hi SpellBad     gui=undercurl guisp=" .. c.error,
    "hi SpellCap     gui=undercurl guisp=" .. c.warn,
    "hi SpellLocal   gui=undercurl guisp=" .. c.info,
    "hi SpellRare    gui=undercurl guisp=" .. c.hint,
  }
  return table.concat(lines, "\n") .. "\n"
end

--- @param bg string
--- @return string
function M.helix(bg)
  local c = palette.get(bg)
  return ([[
# cendre · %s · https://github.com/Aejkatappaja/cendre
# generated by scripts/extras.lua, do not edit
#
# Install: copy to ~/.config/helix/themes/cendre.toml, then set
# `theme = "%s"` in ~/.config/helix/config.toml.

# syntax
"keyword" = "cinder"
"keyword.control" = "cinder"
"keyword.directive" = "cinder"
"keyword.storage" = "cinder"
"operator" = "fg_dim"
"function" = "brass"
"function.builtin" = "brass"
"function.method" = "brass"
"function.macro" = "ember"
"constructor" = "frost"
"type" = "frost"
"type.builtin" = "frost"
"type.enum.variant" = "sap"
"constant" = "fg"
"constant.builtin" = "sap"
"constant.numeric" = "sap"
"constant.character" = "sap"
"constant.character.escape" = "ember"
"string" = "sap"
"string.regexp" = "ember"
"string.special" = "ember"
"comment" = { fg = "comment", modifiers = ["italic"] }
"variable" = "fg"
"variable.builtin" = "cinder"
"variable.parameter" = "ember"
"variable.other.member" = "ember"
"label" = "cinder"
"namespace" = "frost"
"attribute" = "ember"
"punctuation" = "fg_dim"
"punctuation.delimiter" = "fg_dim"
"punctuation.bracket" = "fg_dim"
"special" = "ember"
"tag" = "cinder"

# markup
"markup.heading" = { fg = "ember", modifiers = ["bold"] }
"markup.list" = "ember"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "comment", modifiers = ["underlined"] }
"markup.link.text" = "frost"
"markup.quote" = { fg = "comment", modifiers = ["italic"] }
"markup.raw" = "sap"

# ui
"ui.background" = { bg = "bg0" }
"ui.text" = "fg"
"ui.text.focus" = { fg = "fg", modifiers = ["bold"] }
"ui.cursor" = { fg = "bg0", bg = "ember" }
"ui.cursor.primary" = { fg = "bg0", bg = "ember" }
"ui.cursor.match" = { fg = "ember", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.selection" = { bg = "vis" }
"ui.linenr" = "gutter"
"ui.linenr.selected" = { fg = "ember", modifiers = ["bold"] }
"ui.statusline" = { fg = "fg_dim", bg = "bg2" }
"ui.statusline.inactive" = { fg = "gutter", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "ember", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "ok", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "info", modifiers = ["bold"] }
"ui.bufferline" = { fg = "comment", bg = "bg1" }
"ui.bufferline.active" = { fg = "fg", bg = "bg0", modifiers = ["bold"] }
"ui.popup" = { fg = "fg", bg = "bg_deep" }
"ui.window" = { fg = "bg3" }
"ui.help" = { fg = "fg", bg = "bg_deep" }
"ui.menu" = { fg = "fg", bg = "bg1" }
"ui.menu.selected" = { fg = "bg0", bg = "ember", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg3"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.inlay-hint" = { fg = "gutter", modifiers = ["italic"] }
"ui.highlight" = { bg = "bg2" }

# diagnostics, their own family
"error" = "error"
"warning" = "warn"
"info" = "info"
"hint" = "hint"
"diagnostic.error" = { underline = { color = "error", style = "curl" } }
"diagnostic.warning" = { underline = { color = "warn", style = "curl" } }
"diagnostic.info" = { underline = { color = "info", style = "curl" } }
"diagnostic.hint" = { underline = { color = "hint", style = "curl" } }

# diff
"diff.plus" = "ok"
"diff.minus" = "error"
"diff.delta" = "info"

[palette]
bg_deep = "%s"
bg0 = "%s"
bg1 = "%s"
bg2 = "%s"
bg3 = "%s"
bg4 = "%s"
bg5 = "%s"
fg = "%s"
fg_dim = "%s"
comment = "%s"
gutter = "%s"
vis = "%s"
cinder = "%s"
ember = "%s"
brass = "%s"
sap = "%s"
frost = "%s"
error = "%s"
warn = "%s"
ok = "%s"
hint = "%s"
info = "%s"
]]):format(bg, palette.name(bg),
    c.bg_deep, c.bg0, c.bg1, c.bg2, c.bg3, c.bg4, c.bg5,
    c.fg, c.fg_dim, c.comment, c.gutter, c.vis,
    c.cinder, c.ember, c.brass, c.sap, c.frost,
    c.error, c.warn, c.ok, c.hint, c.info)
end

--- @param bg string
--- @return string
function M.zed(bg)
  local c = palette.get(bg)

  --- @param hex string
  --- @param alpha string|nil two hex digits
  --- @return string
  local function a(hex, alpha)
    return '"' .. hex .. (alpha or "ff") .. '"'
  end

  --- @param scope string
  --- @param hex string
  --- @param style string|nil
  --- @return string
  local function syn(scope, hex, style)
    return ('        "%s": { "color": %s, "font_style": %s, "font_weight": null }')
      :format(scope, a(hex), style and ('"' .. style .. '"') or "null")
  end

  local syntax = {
    syn("comment", c.comment, "italic"),
    syn("comment.doc", c.comment, "italic"),
    syn("keyword", c.cinder),
    syn("operator", c.fg_dim),
    syn("punctuation", c.fg_dim),
    syn("punctuation.bracket", c.fg_dim),
    syn("punctuation.delimiter", c.fg_dim),
    syn("punctuation.special", c.ember),
    syn("function", c.brass),
    syn("function.method", c.brass),
    syn("function.builtin", c.brass),
    syn("constructor", c.frost),
    syn("type", c.frost),
    syn("type.builtin", c.frost),
    syn("string", c.sap),
    syn("string.special", c.ember),
    syn("string.escape", c.ember),
    syn("string.regex", c.ember),
    syn("number", c.sap),
    syn("boolean", c.sap),
    syn("constant", c.fg),
    syn("variable", c.fg),
    syn("variable.special", c.cinder),
    syn("property", c.ember),
    syn("attribute", c.ember),
    syn("label", c.cinder),
    syn("tag", c.cinder),
    syn("emphasis", c.ember),
    syn("emphasis.strong", c.ember),
    syn("link_text", c.frost),
    syn("link_uri", c.comment),
    syn("title", c.ember),
    syn("primary", c.fg),
    syn("predictive", c.gutter, "italic"),
    syn("hint", c.hint),
  }

  return ([[
{
  "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
  "name": "%s",
  "author": "Aejkatappaja",
  "themes": [
    {
      "name": "%s",
      "appearance": "dark",
      "style": {
        "background": %s,
        "editor.background": %s,
        "editor.foreground": %s,
        "editor.gutter.background": %s,
        "editor.line_number": %s,
        "editor.active_line_number": %s,
        "editor.active_line.background": %s,
        "editor.highlighted_line.background": %s,
        "editor.wrap_guide": %s,
        "editor.document_highlight.read_background": %s,
        "editor.document_highlight.write_background": %s,
        "editor.invisible": %s,
        "editor.indent_guide": %s,
        "editor.indent_guide_active": %s,
        "editor.subheader.background": %s,
        "elevated_surface.background": %s,
        "surface.background": %s,
        "text": %s,
        "text.muted": %s,
        "text.placeholder": %s,
        "text.disabled": %s,
        "text.accent": %s,
        "border": %s,
        "border.variant": %s,
        "border.focused": %s,
        "border.selected": %s,
        "border.transparent": %s,
        "border.disabled": %s,
        "element.background": %s,
        "element.hover": %s,
        "element.active": %s,
        "element.selected": %s,
        "element.disabled": %s,
        "ghost_element.background": "#00000000",
        "ghost_element.hover": %s,
        "ghost_element.active": %s,
        "ghost_element.selected": %s,
        "ghost_element.disabled": %s,
        "drop_target.background": %s,
        "title_bar.background": %s,
        "status_bar.background": %s,
        "toolbar.background": %s,
        "tab_bar.background": %s,
        "tab.active_background": %s,
        "tab.inactive_background": %s,
        "panel.background": %s,
        "panel.focused_border": %s,
        "scrollbar.thumb.background": %s,
        "scrollbar.thumb.hover_background": %s,
        "scrollbar.thumb.border": %s,
        "scrollbar.track.background": %s,
        "scrollbar.track.border": %s,
        "terminal.background": %s,
        "terminal.foreground": %s,
        "terminal.bright_foreground": %s,
        "terminal.dim_foreground": %s,
        "terminal.ansi.black": %s,
        "terminal.ansi.red": %s,
        "terminal.ansi.green": %s,
        "terminal.ansi.yellow": %s,
        "terminal.ansi.blue": %s,
        "terminal.ansi.magenta": %s,
        "terminal.ansi.cyan": %s,
        "terminal.ansi.white": %s,
        "terminal.ansi.bright_black": %s,
        "terminal.ansi.bright_red": %s,
        "terminal.ansi.bright_green": %s,
        "terminal.ansi.bright_yellow": %s,
        "terminal.ansi.bright_blue": %s,
        "terminal.ansi.bright_magenta": %s,
        "terminal.ansi.bright_cyan": %s,
        "terminal.ansi.bright_white": %s,
        "error": %s,
        "error.background": %s,
        "error.border": %s,
        "warning": %s,
        "warning.background": %s,
        "warning.border": %s,
        "info": %s,
        "info.background": %s,
        "info.border": %s,
        "hint": %s,
        "hint.background": %s,
        "hint.border": %s,
        "success": %s,
        "success.background": %s,
        "success.border": %s,
        "created": %s,
        "created.background": %s,
        "modified": %s,
        "modified.background": %s,
        "deleted": %s,
        "deleted.background": %s,
        "conflict": %s,
        "ignored": %s,
        "renamed": %s,
        "predictive": %s,
        "players": [
          { "cursor": %s, "background": %s, "selection": %s }
        ],
        "syntax": {
%s
        }
      }
    }
  ]
}
]]):format(
    palette.name(bg), palette.name(bg),
    a(c.bg0), a(c.bg0), a(c.fg), a(c.bg0), a(c.gutter), a(c.ember),
    a(c.bg1), a(c.bg2), a(c.bg3), a(c.bg2), a(c.bg2), a(c.bg4),
    a(c.bg2), a(c.bg4), a(c.bg1),
    a(c.bg_deep), a(c.bg1),
    a(c.fg), a(c.fg_dim), a(c.gutter), a(c.gutter), a(c.ember),
    a(c.bg3), a(c.bg2), a(c.ember), a(c.ember), a(c.bg0), a(c.bg2),
    a(c.bg1), a(c.bg2), a(c.bg3), a(c.vis), a(c.bg1),
    a(c.bg2), a(c.bg3), a(c.vis), a(c.bg1),
    a(c.vis),
    a(c.bg_deep), a(c.bg2), a(c.bg0),
    a(c.bg1), a(c.bg0), a(c.bg1),
    a(c.bg_deep), a(c.ember),
    a(c.bg4), a(c.bg5), a(c.bg3), a(c.bg0), a(c.bg3),
    a(c.bg0), a(c.fg), a(c.fg), a(c.fg_dim),
    a(c.terminal_black), a(c.terminal_red), a(c.terminal_green), a(c.terminal_yellow),
    a(c.terminal_blue), a(c.terminal_magenta), a(c.terminal_cyan), a(c.terminal_white),
    a(c.terminal_bright_black), a(c.terminal_bright_red), a(c.terminal_bright_green),
    a(c.terminal_bright_yellow), a(c.terminal_bright_blue), a(c.terminal_bright_magenta),
    a(c.terminal_bright_cyan), a(c.terminal_bright_white),
    a(c.error), a(c.del), a(c.error),
    a(c.warn), a(c.bg1), a(c.warn),
    a(c.info), a(c.mod), a(c.info),
    a(c.hint), a(c.bg1), a(c.hint),
    a(c.ok), a(c.add), a(c.ok),
    a(c.ok), a(c.add),
    a(c.info), a(c.mod),
    a(c.error), a(c.del),
    a(c.warn), a(c.gutter), a(c.info), a(c.gutter),
    a(c.ember), a(c.ember), a(c.vis),
    table.concat(syntax, ",\n"))
end

return M
