local M = {}

-- Shells, prompts, pagers and TUIs. Diagnostics keep the semantic family
-- everywhere, so a failure never wears a pigment.

local palette = require("cendre.palette")

local LINK = "https://github.com/Aejkatappaja/cendre"
local GENERATED = "# generated by scripts/extras.lua, do not edit"

--- @param hex string
--- @return string "R;G;B" for an SGR truecolor sequence
local function rgb(hex)
  local r, g, b = hex:match("^#(%x%x)(%x%x)(%x%x)$")
  return ("%d;%d;%d"):format(tonumber(r, 16), tonumber(g, 16), tonumber(b, 16))
end

--- @param bg string
--- @return string
function M.fzf(bg)
  local c = palette.get(bg)
  local pairs_ = {
    { "bg+", c.bg1 }, { "bg", c.bg0 }, { "border", c.bg3 },
    { "fg", c.fg_dim }, { "fg+", c.fg }, { "gutter", c.bg0 },
    { "header", c.frost }, { "hl", c.ember }, { "hl+", c.brass },
    { "info", c.comment }, { "marker", c.ok }, { "pointer", c.ember },
    { "prompt", c.cinder }, { "query", c.fg }, { "scrollbar", c.bg3 },
    { "separator", c.bg3 }, { "spinner", c.ember },
  }
  local lines = {}
  for i, kv in ipairs(pairs_) do
    local tail = i == #pairs_ and '"' or " \\"
    table.insert(lines, ("  --color=%s:%s%s"):format(kv[1], kv[2], tail))
  end
  return ([[
# cendre theme for fzf · %s
# %s
%s
#
# Source this file from your shell rc:
#   source /path/to/extras/fzf/cendre.sh

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
%s
]]):format(bg, LINK, GENERATED, table.concat(lines, "\n"))
end

--- @param bg string
--- @return string
function M.eza(bg)
  local c = palette.get(bg)
  -- Filetype and permission keys, each mapped to a pigment by what it means:
  -- directories take the UI accent, anything executable takes the ok green,
  -- anything destructive takes the error red.
  local keys = {
    { "di", c.ember, ";1" }, { "ex", c.ok }, { "fi", c.fg }, { "ln", c.frost },
    { "or", c.error }, { "pi", c.hint }, { "so", c.frost }, { "bd", c.brass },
    { "cd", c.brass }, { "ur", c.brass }, { "uw", c.error }, { "ux", c.ok },
    { "ue", c.ok }, { "gr", c.brass }, { "gw", c.error }, { "gx", c.ok },
    { "tr", c.brass }, { "tw", c.error }, { "tx", c.ok }, { "su", c.cinder },
    { "sf", c.cinder }, { "xa", c.comment }, { "sn", c.fg }, { "sb", c.fg_dim },
    { "uu", c.brass }, { "un", c.fg_dim }, { "gu", c.ember }, { "gn", c.fg_dim },
    { "da", c.comment }, { "in", c.gutter }, { "lc", c.comment }, { "lp", c.frost },
    { "ga", c.ok }, { "gm", c.info }, { "gd", c.error }, { "gv", c.frost },
    { "gt", c.brass }, { "gi", c.gutter }, { "gc", c.warn }, { "hd", c.fg, ";1" },
  }
  local lines = {}
  for i, k in ipairs(keys) do
    local tail = i == #keys and '"' or ":\\"
    table.insert(lines, ("%s=38;2;%s%s%s"):format(k[1], rgb(k[2]), k[3] or "", tail))
  end
  return ([[
# cendre theme for eza (https://eza.rocks) · %s
# %s
%s
#
# Install: source this file from your shell rc.
#   source /path/to/extras/eza/cendre.sh

export EZA_COLORS="\
%s
]]):format(bg, LINK, GENERATED, table.concat(lines, "\n"))
end

--- @param bg string
--- @return string
function M.delta(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for delta (git-delta) · %s
# %s
%s
#
# Add to your .gitconfig:
#   [include]
#     path = /path/to/extras/delta/cendre.gitconfig
#
# For syntax highlighting, install the bat theme too:
#   cp /path/to/extras/bat/cendre.tmTheme "$(bat --config-dir)/themes/"
#   bat cache --build

[delta]
  syntax-theme = %s
  minus-style = syntax "%s"
  minus-emph-style = syntax bold "%s"
  plus-style = syntax "%s"
  plus-emph-style = syntax bold "%s"
  hunk-header-style = "%s" italic
  hunk-header-decoration-style = "%s" box
  file-style = "%s" bold
  file-decoration-style = "%s" ul
  line-numbers-minus-style = "%s"
  line-numbers-plus-style = "%s"
  line-numbers-zero-style = "%s"
  line-numbers-left-style = "%s"
  line-numbers-right-style = "%s"
  commit-decoration-style = "%s" box
  commit-style = "%s" bold
  blame-palette = "%s" "%s" "%s" "%s"
]]):format(bg, LINK, GENERATED,
    palette.name(bg),
    c.del, c.bg3, c.add, c.bg3,
    c.fg_dim, c.bg3,
    c.frost, c.frost,
    c.error, c.ok, c.gutter, c.gutter, c.gutter,
    c.ember, c.brass,
    c.bg0, c.bg1, c.bg2, c.bg3)
end

--- @param bg string
--- @return string
function M.lazygit(bg)
  local c = palette.get(bg)
  return ([[
# cendre · %s · %s
%s
# Merge into ~/.config/lazygit/config.yml

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "%s"
      - "bold"
    inactiveBorderColor:
      - "%s"
    searchingActiveBorderColor:
      - "%s"
      - "bold"
    optionsTextColor:
      - "%s"
    selectedLineBgColor:
      - "%s"
    inactiveViewSelectedLineBgColor:
      - "%s"
    cherryPickedCommitFgColor:
      - "%s"
    cherryPickedCommitBgColor:
      - "%s"
    markedBaseCommitFgColor:
      - "%s"
    markedBaseCommitBgColor:
      - "%s"
    unstagedChangesColor:
      - "%s"
    defaultFgColor:
      - "%s"
]]):format(bg, LINK, GENERATED,
    c.ember, c.comment, c.brass, c.ember,
    c.bg2, c.bg1,
    c.bg0, c.ember,
    c.bg0, c.brass,
    c.error, c.fg)
end

--- @param bg string
--- @return string
function M.btop(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for btop · %s
# %s
%s

theme[main_bg]="%s"
theme[main_fg]="%s"
theme[title]="%s"
theme[hi_fg]="%s"
theme[selected_bg]="%s"
theme[selected_fg]="%s"
theme[inactive_fg]="%s"
theme[graph_text]="%s"
theme[meter_bg]="%s"

theme[proc_misc]="%s"
theme[cpu_box]="%s"
theme[mem_box]="%s"
theme[net_box]="%s"
theme[proc_box]="%s"
theme[div_line]="%s"

# temperature runs cool to hot, so it borrows the palette's own order
theme[temp_start]="%s"
theme[temp_mid]="%s"
theme[temp_end]="%s"

theme[cpu_start]="%s"
theme[cpu_mid]="%s"
theme[cpu_end]="%s"

theme[free_start]="%s"
theme[free_mid]="%s"
theme[free_end]="%s"

theme[cached_start]="%s"
theme[cached_mid]="%s"
theme[cached_end]="%s"

theme[available_start]="%s"
theme[available_mid]="%s"
theme[available_end]="%s"

theme[used_start]="%s"
theme[used_mid]="%s"
theme[used_end]="%s"

theme[download_start]="%s"
theme[download_mid]="%s"
theme[download_end]="%s"

theme[upload_start]="%s"
theme[upload_mid]="%s"
theme[upload_end]="%s"

theme[process_start]="%s"
theme[process_mid]="%s"
theme[process_end]="%s"
]]):format(bg, LINK, GENERATED,
    c.bg0, c.fg, c.fg, c.ember, c.bg2, c.fg, c.comment, c.fg_dim, c.bg3,
    c.ember, c.ember, c.frost, c.sap, c.brass, c.bg3,
    c.frost, c.brass, c.cinder,
    c.frost, c.brass, c.cinder,
    c.sap, c.sap, c.ok,
    c.frost, c.frost, c.hint,
    c.brass, c.ember, c.brass,
    c.frost, c.ember, c.cinder,
    c.frost, c.hint, c.frost,
    c.ember, c.brass, c.ember,
    c.ember, c.sap, c.ok)
end

--- @param bg string
--- @return string
function M.yazi(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for Yazi · %s
# %s
%s

[manager]
cwd = { fg = "%s" }
hovered = { bg = "%s" }
preview_hovered = { bg = "%s" }
find_keyword = { fg = "%s", bold = true }
find_position = { fg = "%s", italic = true }
marker_selected = { fg = "%s", bg = "%s" }
marker_copied = { fg = "%s", bg = "%s" }
marker_cut = { fg = "%s", bg = "%s" }
tab_active = { fg = "%s", bg = "%s" }
tab_inactive = { fg = "%s", bg = "%s" }
border_symbol = "│"
border_style = { fg = "%s" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "%s", bg = "%s" }
mode_normal = { fg = "%s", bg = "%s", bold = true }
mode_select = { fg = "%s", bg = "%s", bold = true }
mode_unset = { fg = "%s", bg = "%s", bold = true }
progress_label = { fg = "%s" }
progress_normal = { fg = "%s" }
progress_error = { fg = "%s" }

[input]
border = { fg = "%s" }
title = {}
value = {}
selected = { reversed = true }

[select]
border = { fg = "%s" }
active = { fg = "%s" }
inactive = {}

[tasks]
border = { fg = "%s" }
title = {}
hovered = { underline = true }

[which]
mask = { bg = "%s" }
cand = { fg = "%s" }
rest = { fg = "%s" }
desc = { fg = "%s" }
separator = "  "
separator_style = { fg = "%s" }

[help]
on = { fg = "%s" }
run = { fg = "%s" }
hovered = { reversed = true, bold = true }
footer = { fg = "%s", bg = "%s" }
]]):format(bg, LINK, GENERATED,
    c.ember, c.bg1, c.bg1, c.brass, c.ember,
    c.ember, c.ember, c.ok, c.ok, c.error, c.error,
    c.fg, c.bg1, c.comment, c.bg_deep, c.bg3,
    c.bg2, c.bg2,
    c.bg0, c.ember, c.bg0, c.info, c.bg0, c.error,
    c.fg, c.bg3, c.error,
    c.ember, c.ember, c.ember, c.ember,
    c.bg_deep, c.hint, c.fg_dim, c.fg, c.bg3,
    c.ember, c.sap, c.fg_dim, c.bg2)
end

--- @param bg string
--- @return string
function M.opencode(bg)
  local c = palette.get(bg)
  local defs = {
    { "bg", c.bg0 }, { "bgFloat", c.bg_deep }, { "bgElevated", c.bg1 },
    { "bgCursorline", c.bg1 }, { "bgSelection", c.vis }, { "border", c.bg3 },
    { "fg", c.fg }, { "fgDim", c.fg_dim }, { "fgComment", c.comment },
    { "fgGutter", c.gutter },
    { "cinder", c.cinder }, { "ember", c.ember }, { "brass", c.brass },
    { "sap", c.sap }, { "frost", c.frost },
    { "error", c.error }, { "warning", c.warn }, { "success", c.ok },
    { "info", c.info }, { "hint", c.hint },
    { "gitAdd", c.ok }, { "gitDelete", c.error }, { "gitChange", c.info },
  }
  local uses = {
    { "primary", "ember" }, { "secondary", "frost" }, { "accent", "brass" },
    { "text", "fg" }, { "textMuted", "fgDim" },
    { "background", "bg" }, { "backgroundPanel", "bgFloat" },
    { "backgroundElement", "bgElevated" },
    { "border", "border" }, { "borderActive", "ember" }, { "borderSubtle", "border" },
    { "error", "error" }, { "warning", "warning" }, { "success", "success" },
    { "info", "info" },
    { "diffAdded", "gitAdd" }, { "diffRemoved", "gitDelete" },
    { "diffContext", "fgDim" }, { "diffHunkHeader", "fgComment" },
    { "diffHighlightAdded", "success" }, { "diffHighlightRemoved", "error" },
    { "diffAddedBg", "bgElevated" }, { "diffRemovedBg", "bgElevated" },
    { "diffContextBg", "bg" }, { "diffLineNumber", "fgGutter" },
    { "markdownText", "fg" }, { "markdownHeading", "ember" },
    { "markdownLink", "frost" }, { "markdownLinkText", "frost" },
    { "markdownCode", "sap" }, { "markdownBlockQuote", "fgComment" },
    { "markdownEmph", "ember" }, { "markdownStrong", "brass" },
    { "markdownHorizontalRule", "border" }, { "markdownListItem", "ember" },
    { "markdownCodeBlock", "sap" },
    { "syntaxComment", "fgComment" }, { "syntaxKeyword", "cinder" },
    { "syntaxFunction", "brass" }, { "syntaxVariable", "fg" },
    { "syntaxString", "sap" }, { "syntaxNumber", "sap" },
    { "syntaxType", "frost" }, { "syntaxOperator", "fgDim" },
    { "syntaxPunctuation", "fgDim" },
  }

  local dl, ul = {}, {}
  for i, d in ipairs(defs) do
    table.insert(dl, ('    "%s": "%s"%s'):format(d[1], d[2], i < #defs and "," or ""))
  end
  for i, u in ipairs(uses) do
    table.insert(ul, ('    "%s": "%s"%s'):format(u[1], u[2], i < #uses and "," or ""))
  end

  return ([[
{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
%s
  },
  "theme": {
%s
  }
}
]]):format(table.concat(dl, "\n"), table.concat(ul, "\n"))
end

--- @param bg string
--- @return string
function M.hunk(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for Hunk · %s
# %s
%s
#
# Install: copy into ~/.config/hunk/config.toml, or merge the [custom_theme]
# block below and set `theme = "custom"`.

theme = "custom"

[custom_theme]
base  = "github-dark-default"  # unset keys inherit from this built-in theme
label = "%s"

background = "%s"
panel      = "%s"
panelAlt   = "%s"
border     = "%s"
accent     = "%s"
accentMuted = "%s"
text       = "%s"
muted      = "%s"

addedBg        = "%s"
removedBg      = "%s"
movedAddedBg   = "%s"
movedRemovedBg = "%s"
contextBg      = "%s"

added    = "%s"
removed  = "%s"
context  = "%s"
lineNumber = "%s"
]]):format(bg, LINK, GENERATED,
    palette.name(bg),
    c.bg0, c.bg_deep, c.bg1, c.bg3, c.ember, c.fg_dim, c.fg, c.comment,
    c.add, c.del, c.mod, c.bg2, c.bg0,
    c.ok, c.error, c.fg_dim, c.gutter)
end

--- @param bg string
--- @return string
function M.herdr(bg)
  local c = palette.get(bg)
  return ([[
# cendre theme for herdr (https://herdr.dev) · %s
# %s
%s
#
# Install: copy into ~/.config/herdr/config.toml, or merge the [theme] and
# [theme.custom] blocks below into your existing config.

[theme]
name = "terminal"   # neutral base; every token below is overridden by cendre
auto_switch = false

[theme.custom]
accent      = "%s"
panel_bg    = "%s"
surface0    = "%s"
surface1    = "%s"
surface_dim = "%s"
overlay0    = "%s"
overlay1    = "%s"
text        = "%s"
subtext0    = "%s"
mauve       = "%s"
green       = "%s"
yellow      = "%s"
red         = "%s"
blue        = "%s"
teal        = "%s"
peach       = "%s"
]]):format(bg, LINK, GENERATED,
    c.ember, c.bg0, c.bg1, c.bg2, c.bg_deep,
    c.comment, c.fg_dim, c.fg, c.fg_dim,
    c.cinder, c.sap, c.brass, c.error, c.frost, c.hint, c.ember)
end

--- @param bg string
--- @return string
function M.starship(bg)
  local c = palette.get(bg)
  return ([[
# cendre palette for Starship · %s
# %s
%s
#
# Install: copy into ~/.config/starship.toml, or if you keep your own config,
# copy the [palettes.%s] block and add `palette = "%s"` at the top.

palette = "%s"

[palettes.%s]
bg      = "%s"
fg      = "%s"
fg_dim  = "%s"
comment = "%s"
cinder  = "%s"
ember   = "%s"
brass   = "%s"
sap     = "%s"
frost   = "%s"
error   = "%s"
warning = "%s"
ok      = "%s"
info    = "%s"

[directory]
style = "ember bold"

[git_branch]
style = "cinder"

[git_status]
style = "warning"

[cmd_duration]
style = "comment"

[character]
success_symbol = "[❯](ember)"
error_symbol = "[❯](error)"
vimcmd_symbol = "[❮](sap)"

[nodejs]
style = "sap"

[golang]
style = "frost"

[rust]
style = "cinder"

[python]
style = "brass"

[lua]
style = "frost"
]]):format(bg, LINK, GENERATED,
    palette.name(bg), palette.name(bg),
    palette.name(bg), palette.name(bg),
    c.bg0, c.fg, c.fg_dim, c.comment,
    c.cinder, c.ember, c.brass, c.sap, c.frost,
    c.error, c.warn, c.ok, c.info)
end

--- Slack takes ten comma-separated hex values in a fixed order.
--- @param bg string
--- @return string
function M.slack(bg)
  local c = palette.get(bg)
  return table.concat({
    c.bg0,   -- column bg
    c.bg_deep, -- menu bg
    c.ember, -- active item
    c.bg0,   -- active item text
    c.bg2,   -- hover item
    c.fg,    -- text
    c.ok,    -- active presence
    c.error, -- mention badge
    c.bg0,   -- top nav bg
    c.fg,    -- top nav text
  }, ",") .. "\n"
end

--- @param bg string
--- @return string
function M.obsidian(bg)
  local c = palette.get(bg)
  return ([[
/* cendre for Obsidian · %s
   %s
   generated by scripts/extras.lua, do not edit

   Install: copy this folder to <vault>/.obsidian/themes/cendre, then pick
   cendre under Appearance. Dark only, like the colorscheme. */

.theme-dark {
  --background-primary: %s;
  --background-primary-alt: %s;
  --background-secondary: %s;
  --background-secondary-alt: %s;
  --background-modifier-border: %s;
  --background-modifier-border-hover: %s;
  --background-modifier-hover: %s;
  --background-modifier-error: %s;
  --background-modifier-success: %s;

  --text-normal: %s;
  --text-muted: %s;
  --text-faint: %s;
  --text-accent: %s;
  --text-accent-hover: %s;
  --text-on-accent: %s;
  --text-selection: %s;
  --text-highlight-bg: %s;
  --text-error: %s;
  --text-success: %s;

  --interactive-accent: %s;
  --interactive-accent-hover: %s;
  --interactive-normal: %s;
  --interactive-hover: %s;

  --h1-color: %s;
  --h2-color: %s;
  --h3-color: %s;
  --h4-color: %s;
  --h5-color: %s;
  --h6-color: %s;

  --code-normal: %s;
  --code-background: %s;
  --code-keyword: %s;
  --code-function: %s;
  --code-string: %s;
  --code-value: %s;
  --code-comment: %s;
  --code-property: %s;
  --code-tag: %s;
  --code-operator: %s;

  --blockquote-border-color: %s;
  --hr-color: %s;
  --tag-color: %s;
  --tag-background: %s;
  --checkbox-color: %s;
  --link-color: %s;
  --link-unresolved-color: %s;
  --graph-line: %s;
  --graph-node: %s;
  --graph-node-tag: %s;
}
]]):format(bg, LINK,
    c.bg0, c.bg1, c.bg_deep, c.bg1, c.bg3, c.bg4, c.bg1, c.del, c.add,
    c.fg, c.fg_dim, c.comment, c.ember, c.brass, c.bg0, c.vis, c.vis,
    c.error, c.ok,
    c.ember, c.brass, c.bg2, c.bg3,
    c.ember, c.brass, c.frost, c.sap, c.cinder, c.fg_dim,
    c.fg, c.bg_deep, c.cinder, c.brass, c.sap, c.sap, c.comment,
    c.ember, c.cinder, c.fg_dim,
    c.ember, c.bg3, c.frost, c.bg1, c.ember, c.frost, c.error,
    c.bg3, c.ember, c.frost)
end

--- @param bg string
--- @return string
function M.obsidian_manifest(bg)
  return ([[
{
  "name": "%s",
  "version": "1.0.0",
  "minAppVersion": "1.0.0",
  "author": "Aejkatappaja",
  "authorUrl": "%s"
}
]]):format(palette.name(bg), LINK)
end

--- Firefox reads a WebExtension manifest, which is the only shape a theme can
--- take there. Loaded from about:debugging until it is on addons.mozilla.org.
--- @param bg string
--- @return string
function M.firefox(bg)
  local c = palette.get(bg)
  return ([[
{
  "manifest_version": 2,
  "name": "%s",
  "version": "1.0.0",
  "description": "One wood fire, taken apart. %s",
  "theme": {
    "colors": {
      "frame": "%s",
      "frame_inactive": "%s",
      "tab_background_text": "%s",
      "tab_selected": "%s",
      "tab_text": "%s",
      "tab_line": "%s",
      "tab_loading": "%s",
      "toolbar": "%s",
      "toolbar_text": "%s",
      "toolbar_field": "%s",
      "toolbar_field_text": "%s",
      "toolbar_field_border": "%s",
      "toolbar_field_focus": "%s",
      "toolbar_field_highlight": "%s",
      "toolbar_top_separator": "%s",
      "toolbar_bottom_separator": "%s",
      "toolbar_vertical_separator": "%s",
      "popup": "%s",
      "popup_text": "%s",
      "popup_border": "%s",
      "popup_highlight": "%s",
      "popup_highlight_text": "%s",
      "ntp_background": "%s",
      "ntp_text": "%s",
      "sidebar": "%s",
      "sidebar_text": "%s",
      "sidebar_border": "%s",
      "sidebar_highlight": "%s",
      "sidebar_highlight_text": "%s",
      "bookmark_text": "%s",
      "button_background_hover": "%s",
      "button_background_active": "%s",
      "icons": "%s",
      "icons_attention": "%s"
    },
    "properties": {
      "color_scheme": "dark",
      "content_color_scheme": "dark"
    }
  }
}
]]):format(palette.name(bg), LINK,
    c.bg_deep, c.bg_deep, c.comment, c.bg0, c.fg, c.ember, c.ember,
    c.bg0, c.fg, c.bg1, c.fg, c.bg3, c.bg1, c.vis,
    c.bg3, c.bg3, c.bg3,
    c.bg_deep, c.fg, c.bg3, c.ember, c.bg0,
    c.bg0, c.fg,
    c.bg_deep, c.fg_dim, c.bg3, c.ember, c.bg0,
    c.fg_dim, c.bg1, c.bg2, c.fg_dim, c.ember)
end

--- bat reads a Sublime Text tmTheme, which is an XML property list. Scopes are
--- grouped the way the Neovim treesitter map groups them.
--- @param bg string
--- @return string
function M.bat(bg)
  local c = palette.get(bg)

  --- @param name string
  --- @param scope string|nil
  --- @param fg string|nil
  --- @param bgc string|nil
  --- @param style string|nil
  --- @return string
  local function rule(name, scope, fg, bgc, style)
    local settings = {}
    if fg then table.insert(settings, ("\t\t\t\t<key>foreground</key>\n\t\t\t\t<string>%s</string>"):format(fg)) end
    if bgc then table.insert(settings, ("\t\t\t\t<key>background</key>\n\t\t\t\t<string>%s</string>"):format(bgc)) end
    if style then table.insert(settings, ("\t\t\t\t<key>fontStyle</key>\n\t\t\t\t<string>%s</string>"):format(style)) end
    local head = ("\t\t<dict>\n\t\t\t<key>name</key>\n\t\t\t<string>%s</string>\n"):format(name)
    if scope then
      head = head .. ("\t\t\t<key>scope</key>\n\t\t\t<string>%s</string>\n"):format(scope)
    end
    return head .. "\t\t\t<key>settings</key>\n\t\t\t<dict>\n"
      .. table.concat(settings, "\n") .. "\n\t\t\t</dict>\n\t\t</dict>"
  end

  local global = ("\t\t<dict>\n\t\t\t<key>settings</key>\n\t\t\t<dict>\n"
    .. "\t\t\t\t<key>background</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>foreground</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>caret</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>lineHighlight</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>selection</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>gutterForeground</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t\t<key>invisibles</key>\n\t\t\t\t<string>%s</string>\n"
    .. "\t\t\t</dict>\n\t\t</dict>"):format(c.bg0, c.fg, c.ember, c.bg1, c.vis, c.gutter, c.bg3)

  local rules = {
    global,
    rule("Comment", "comment, punctuation.definition.comment", c.comment, nil, "italic"),
    rule("String", "string, string.quoted", c.sap),
    rule("String escape", "constant.character.escape", c.ember),
    rule("Regex", "string.regexp", c.ember),
    rule("Number", "constant.numeric", c.sap),
    rule("Boolean and null", "constant.language", c.sap),
    rule("Constant", "constant.other, variable.other.constant", c.fg),
    rule("Keyword", "keyword, storage.type, storage.modifier", c.cinder),
    rule("Operator", "keyword.operator, punctuation.separator, punctuation.terminator", c.fg_dim),
    rule("Punctuation", "punctuation.section, meta.brace", c.fg_dim),
    rule("Function", "entity.name.function, support.function, meta.function-call", c.brass),
    rule("Macro", "entity.name.macro, meta.preprocessor", c.ember),
    rule("Type", "entity.name.type, entity.name.class, support.type, support.class", c.frost),
    rule("Namespace", "entity.name.namespace, entity.name.module", c.frost),
    rule("Variable", "variable, variable.other", c.fg),
    rule("Parameter", "variable.parameter", c.ember),
    rule("Property", "variable.other.member, meta.object-literal.key, support.type.property-name", c.ember),
    rule("Builtin variable", "variable.language", c.cinder),
    rule("Tag", "entity.name.tag", c.cinder),
    rule("Tag attribute", "entity.other.attribute-name", c.ember),
    rule("Decorator", "meta.decorator, punctuation.definition.decorator", c.ember),
    rule("Heading", "markup.heading", c.ember, nil, "bold"),
    rule("Markup bold", "markup.bold", c.brass, nil, "bold"),
    rule("Markup italic", "markup.italic", c.fg, nil, "italic"),
    rule("Markup link", "markup.underline.link", c.frost, nil, "underline"),
    rule("Markup raw", "markup.raw, markup.inline.raw", c.sap),
    rule("Markup quote", "markup.quote", c.comment, nil, "italic"),
    rule("Markup list", "markup.list punctuation.definition", c.ember),
    rule("Diff added", "markup.inserted", c.ok),
    rule("Diff removed", "markup.deleted", c.error),
    rule("Diff changed", "markup.changed", c.info),
    rule("Invalid", "invalid, invalid.illegal", c.error),
    rule("Deprecated", "invalid.deprecated", c.warn),
  }

  return ([[
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>%s</string>
	<key>semanticClass</key>
	<string>theme.dark.%s</string>
	<key>uuid</key>
	<string>%s</string>
	<key>colorSpaceName</key>
	<string>sRGB</string>
	<key>author</key>
	<string>Aejkatappaja</string>
	<key>settings</key>
	<array>
%s
	</array>
</dict>
</plist>
]]):format(palette.name(bg), palette.name(bg),
    ("3f7a1c6e-4b21-4d8f-9c3a-%s"):format(bg == palette.default and "cendre000001"
      or (bg == "medium" and "cendre000002" or "cendre000003")),
    table.concat(rules, "\n"))
end

return M
